version: "3.9"

services:
  whisper-api:
    image: msoo.ces.myfiinet.com:6702/morioka/tiny-openai-whisper-api
    # build: .
    container_name: whisper-api
    restart: unless-stopped
    init: true
    volumes:
      - ./main.py:/app/main.py
      - /data/.cache/whisper:/cache/whisper
    ports:
      - 6614:8000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 2
              capabilities: [ gpu ]
