version: "3.9"
# docker compose -f docker-compose_timestamped.yml up
services:
  whisper-api:
    image: msoo.ces.myfiinet.com:6702/morioka/tiny-openai-whisper-api:0.1.2.timestamped
    build: .
    container_name: whisper-api
    restart: unless-stopped
    init: true
    # environment:
    #   - HTTP_PROXY=http://IG2074:QMMR8ftb@10.36.6.66:3128
    #   - HTTPS_PROXY=http://IG2074:QMMR8ftb@10.36.6.66:3128

    volumes:
      - ./main_timestamped.py:/app/main.py
      - /data/.cache/whisper:/cache/whisper
    ports:
      - 6615:8000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              # count: 2
              device_ids: [ "1" ]
              capabilities: [ gpu ]
